modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0-only"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "Kyllian"
description = '''
Server-side store GUI for PayNow, allowing players to browse and purchase products in-game.
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${mod_mc_compat}"
ordering = "NONE"
side = "BOTH"
