plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
    mavenLocal()
    maven { url 'https://jitpack.io' }
}

dependencies {
    api 'gg.paynow:java-sdk:1.0.72'
    implementation 'com.squareup.okhttp3:okhttp:5.2.1'
    implementation 'com.squareup.okhttp3:logging-interceptor:5.2.1'
}
